BOT-TOKEN: ''

database:
  host: 'localhost'
  port: 3306
  name: 'WoS'
  username: 'root'
  password: 'HektorTM'

housepoint-channel: 'ID'
warning-channel: 'ID'

discord:
  webhook:
    error: ''
    warning: ''