name: WoSCore
version: '1.3'
main: me.hektortm.wosCore.WoSCore
api-version: '1.21'
commands:
  core:
    description: core commands
    usage: /core <reload>
    permission: core.use
  gui:
    description: create or access a gui
    usage: /gui