name: WoS_Core
version: '1.0'
main: me.hektortm.wosCore.WoSCore
api-version: '1.21'
commands:
  core:
    description: core commands
    usage: /core <reload>
    permission: core.use
# Essentials
  gmc:
    description: set your gamemode to creative
    usage: /gmc [player]
    permission: essentials.gmc
    aliases:
      - creative
  gms:
    description: set your gamemode to survival
    usage: /gms [player]
    permission: essentials.gms
    aliases:
      - survival
  gma:
    description: set your gamemode to adventure
    usage: /gma [player]
    permission: essentials.gma
    aliases:
      - adventure
  gmsp:
    description: set your gamemode to spectator
    usage: /gmsp [player]
    permission: essentials.gmsp
    aliases:
      - spectator
  fly:
    description: toggle fly
    usage: /fly [player]
    permission: essentials.fly
  speed:
    description: change your speed
    usage: /speed <0-10> [player]
    permission: essentials.speed
  tp:
    description: teleport to a player
    usage: /tp <player>
    permission: essentials.tp
  tphere:
    description: teleport a player to you
    usage: /tphere <player>
    permission: essentials.tphere
  day:
    description: set the time to day
    usage: /day
    permission: essentials.day
  night:
    description: set the time to night
    usage: /night
    permission: essentials.night
  ptime:
    description: set your personal time
    usage: /ptime [day|night|number]
    permission: essentials.ptime
  sun:
    description: change the weather to sunny
    usage: /sun
    permission: essentials.sun
  rain:
    description: change the weather to sunny
    usage: /rain
    permission: essentials.rain
  storm:
    description: change the weather to sunny
    usage: /storm
    permission: essentials.storm
  broadcast:
    aliases:
      - bc
    description: send a broadcast
    usage: /broadcast <message>
    permission: essentials.broadcast
  shout:
    description: shout a message
    usage: /shout <message>
    permission: essentials.shout
# pvp System
  pvp:
    description: combat system commands
    usage: /pvp [toggle|status|help]
#
  playtime:
    description: Check your playtime
    usage: /playtime
